### ISSUE TITLE
Replica index can't be deleted

### ISSUE THREAD

**Issue by k-yomo** [k-yomo/terraform-provider-algolia#103]
Currently we can't delete virtual index from terraform.
It seems like the API issue, since it can't be deleted from the other clients too.
https://github.com/algolia/algoliasearch-client-javascript/issues/1377

NOTE: 
- We are following the below steps to delete replica index.
https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/deleting-replicas/?client=go#using-the-api

- Skipping some of the tests due to the issue.
https://github.com/k-yomo/terraform-provider-algolia/blob/main/internal/provider/resource_index_test.go#L87-L91
https://github.com/k-yomo/terraform-provider-algolia/blob/main/internal/provider/resource_virtual_index_test.go#L10-L14

Workaround would be deleting replica from console, and remove from the state with `terraform state rm`.

### Terraform Version
- Terraform version: v1.0.0
- Provider version: v0.5.0

### Affected Resource(s)
- algolia_index
- algolia_virtual_index

### Terraform Configuration Files
```diff
# algolia_index.example_replica will be destroyed
- resource "algolia_index" "example_replica" {
    - id                     = "test" -> null
    - name                   = "test" -> null
    - virtual                = false -> null
    ...
}
```

### Expected Behavior
Replica index should be deleted when we delete a replica index resource.

### Actual Behavior
We'll get the following error.
```
Algolia API error [403] cannot apply a add object request on a replica index
```

### Steps to Reproduce
Deleting replica index resource.

### References
- https://github.com/algolia/algoliasearch-client-javascript/issues/1377

**Comment by dotSource-bke** [comment]
We saw that the replica indices have to be unlinked from the primary index before atempting to delete them.
Still we were not able to do this "manually" by reapplying the primary without the replica to delete and then atempting to delete the replica. Even worse, when deleting indices that are linked to replicas, instead of becomming independend indices, the replicas drop into an orphaned state, where it is impossible to delete them (as they still count as replica) but also impossible to unlink (as the primary is gone). We needed to relink the replicas to a primary and then unlink using a different method than terraform.
