### ISSUE TITLE
Missing dependency to primary index

### ISSUE THREAD

**Issue by greg0ire** [k-yomo/terraform-provider-algolia#134]
### Terraform Version
- Terraform version: v0.14.6
- Provider version: v0.5.4

### Affected Resource(s)

- algolia_index
- algolia_virtual_index

### Terraform Configuration Files
Copy-paste your Terraform configurations here
```hcl

resource "algolia_index" "my_index" {
…
}

resource "algolia_virtual_index" "product_index" {
  name               = "my_replica"
  primary_index_name = "my_index"
  …
}
```

### Expected Behavior
The primary should be created first, then all the replicas

### Actual Behavior
There was an attempt to create everything in parallel, which failed: only the primary was created and the replica creation failed with a 404 when attempting to get the settings of the primary, which did not exist yet

### Steps to Reproduce

Terraform a non-existent primary and its replica.

### Important Factoids

@julienpa and @godelized helped me troubleshoot this yesterday evening, and today, @godelized provided me with 2 workarounds:

- use `primary_name = algolia_index.<primary_resource_name>.name`
- use `depends_on = [algolia_index.<primary_resource_name>]`

Would there be a way to express that dependency implicitly, directly in the source code of this plugin? I can't think of a reason not to express it if it's possible..

### References
None.

**Comment by k-yomo** [comment]
@greg0ire 
Thank you for reporting!  There is no way for a replica to have an implicit dependency with the current architecture.
This is not implicit dependency but we can force to have a dependency if we change it like below.
https://github.com/k-yomo/terraform-provider-algolia/issues/135#issuecomment-1259301129

**Comment by greg0ire** [comment]
To follow up on this, today I tried terraforming an application from scratch, and I also experience it with query suggestion indices (which I didn't mention).

**Comment by k-yomo** [comment]
Thanks for sharing!  I think there is no way to handle this unless we manage all dependencies in the same resource which is not possible sometimes like that (index and query suggestion).

It happens with the other providers like GCP or AWS.
I think the best practice is to reference by resource name as you mention which make it possible for terraform to resolve dependencies and order of application.
`primary_name = algolia_index.<primary_resource_name>.name`

Let me close this issue because it is rather nature of managing resources in terraform than provider's bug...!
